version: '3.9'
services:
  mysql-server:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: ocp_database
      MYSQL_USER: root
      MYSQL_PASSWORD: 0000
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  ocp-backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - mysql-server
    environment:
      DB_HOST: mysql-server
      DB_USER: root
      DB_PASSWORD: 0000
      DB_NAME: ocp_database

  ocp-frontend:
    build: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
    depends_on:
      - ocp-backend

volumes:
  db_data:
